<?xml version="1.0"?>
<robot name="squeak_mouse" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="body_len" value="0.15"/>
    <xacro:property name="body_width" value="0.10"/>
    <xacro:property name="body_height" value="0.06"/>
    <xacro:property name="body_mass" value="0.5"/>

    <xacro:property name="wheel_radius" value="0.035"/>
    <xacro:property name="wheel_width" value="0.01"/>
    <xacro:property name="wheel_mass" value="0.1"/>

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>
    <material name="pink">
        <color rgba="1 0.6 0.6 1"/> </material>
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <xacro:macro name="box_inertia" params="m x y z">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
                     iyy="${m*(x*x+z*z)/12}" iyz="0"
                     izz="${m*(x*x+y*y)/12}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
                     iyy="${m*(3*r*r+h*h)/12}" iyz="0"
                     izz="${m*r*r/2}"/>
        </inertial>
    </xacro:macro>
    
    <xacro:macro name="sphere_inertia" params="m r">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${2*m*r*r/5}" ixy="0" ixz="0"
                     iyy="${2*m*r*r/5}" iyz="0"
                     izz="${2*m*r*r/5}"/>
        </inertial>
    </xacro:macro>

    <link name="base_link">
        <visual>
            <geometry><box size="${body_len} ${body_width} ${body_height}"/></geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry><box size="${body_len} ${body_width} ${body_height}"/></geometry>
        </collision>
        <xacro:box_inertia m="${body_mass}" x="${body_len}" y="${body_width}" z="${body_height}"/>
    </link>
    
    <gazebo reference="base_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <xacro:macro name="ear" params="prefix y_pos">
        <link name="${prefix}_ear">
            <visual>
                <origin xyz="0 0 0" rpy="1.5707 0 0"/>
                <geometry><cylinder radius="0.03" length="0.005"/></geometry>
                <material name="pink"/>
            </visual>
            <xacro:cylinder_inertia m="0.05" r="0.03" h="0.005"/>
        </link>

        <joint name="${prefix}_ear_joint" type="fixed">
            <parent link="base_link"/>
            <child link="${prefix}_ear"/>
            <origin xyz="0.04 ${y_pos} ${body_height/2 + 0.02}" rpy="0 0 0"/>
        </joint>
        
        <gazebo reference="${prefix}_ear">
            <material>Gazebo/RedBright</material>
        </gazebo>
    </xacro:macro>

    <xacro:ear prefix="left" y_pos="0.04"/>
    <xacro:ear prefix="right" y_pos="-0.04"/>

    <link name="tail">
        <visual>
            <origin xyz="-0.06 0 0" rpy="0 1.57 0"/> <geometry><cylinder radius="0.005" length="0.12"/></geometry>
            <material name="pink"/>
        </visual>
        <xacro:cylinder_inertia m="0.05" r="0.005" h="0.12"/>
    </link>
    
    <joint name="tail_joint" type="fixed">
        <parent link="base_link"/>
        <child link="tail"/>
        <origin xyz="-${body_len/2} 0 0" rpy="0 0 0.2"/> </joint>

    <xacro:macro name="wheel" params="prefix y_pos">
        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="1.5707 0 0"/>
                <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="1.5707 0 0"/>
                <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
            </collision>
            <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="0.03 ${y_pos} -0.02" rpy="0 0 0"/> <axis xyz="0 1 0"/>
        </joint>
        
        <gazebo reference="${prefix}_wheel">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>

    <xacro:wheel prefix="left" y_pos="0.06"/>
    <xacro:wheel prefix="right" y_pos="-0.06"/>

    <link name="caster_wheel">
        <visual>
            <geometry><sphere radius="${wheel_radius/2}"/></geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry><sphere radius="${wheel_radius/2}"/></geometry>
        </collision>
        <xacro:sphere_inertia m="0.05" r="${wheel_radius/2}"/>
    </link>

    <joint name="caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel"/>
        <origin xyz="-0.06 0 -0.035" rpy="0 0 0"/>
    </joint>

    <gazebo reference="caster_wheel">
        <mu1>0.001</mu1>
        <mu2>0.001</mu2>
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo>
        <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
            
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>
            <wheel_separation>0.12</wheel_separation>
            <wheel_diameter>${wheel_radius * 2}</wheel_diameter>

            <max_wheel_torque>10</max_wheel_torque>
            <max_wheel_acceleration>1.0</max_wheel_acceleration>

            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_link</robot_base_frame>
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>

        </plugin>
    </gazebo>

</robot>