<?xml version="1.0"?>
<robot name="doraemon_cat" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="torso_len" value="0.4"/>
    <xacro:property name="torso_width" value="0.2"/>
    <xacro:property name="torso_height" value="0.15"/>
    <xacro:property name="torso_mass" value="5.0"/>

    <xacro:property name="head_size" value="0.15"/>
    <xacro:property name="wheel_radius" value="0.08"/>
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="wheel_mass" value="1.0"/>
    <xacro:property name="caster_radius" value="0.04"/>

    <material name="dora_blue"><color rgba="0.0 0.6 0.9 1"/></material>
    <material name="dora_white"><color rgba="1 1 1 1"/></material>
    <material name="dora_red"><color rgba="0.9 0.1 0.1 1"/></material>
    <material name="dora_yellow"><color rgba="1 0.8 0.1 1"/></material>
    <material name="black"><color rgba="0 0 0 1"/></material>
    <material name="silver"><color rgba="0.75 0.75 0.75 1"/></material>

    <xacro:macro name="box_inertia" params="m x y z">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/> <mass value="${m}"/>
            <inertia ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
                     iyy="${m*(x*x+z*z)/12}" iyz="0"
                     izz="${m*(x*x+y*y)/12}"/>
        </inertial>
    </xacro:macro>
    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/> <mass value="${m}"/>
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
                     iyy="${m*(3*r*r+h*h)/12}" iyz="0"
                     izz="${m*r*r/2}"/>
        </inertial>
    </xacro:macro>
    <xacro:macro name="sphere_inertia" params="m r">
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/> <mass value="${m}"/>
            <inertia ixx="${2*m*r*r/5}" ixy="0" ixz="0"
                     iyy="${2*m*r*r/5}" iyz="0"
                     izz="${2*m*r*r/5}"/>
        </inertial>
    </xacro:macro>

    <link name="base_link">
        <visual>
            <geometry><box size="${torso_len} ${torso_width} ${torso_height}"/></geometry>
            <material name="dora_blue"/>
        </visual>
        <collision>
            <geometry><box size="${torso_len} ${torso_width} ${torso_height}"/></geometry>
        </collision>
        <xacro:box_inertia m="${torso_mass}" x="${torso_len}" y="${torso_width}" z="${torso_height}"/>
    </link>
    <gazebo reference="base_link"><material>Gazebo/SkyBlue</material></gazebo>

    <link name="pocket">
        <visual>
            <geometry><box size="0.01 0.14 0.10"/></geometry>
            <material name="dora_white"/>
        </visual>
    </link>
    <joint name="pocket_joint" type="fixed">
        <parent link="base_link"/>
        <child link="pocket"/>
        <origin xyz="${torso_len/2 + 0.001} 0 0" rpy="0 0 0"/>
    </joint>
    <gazebo reference="pocket"><material>Gazebo/White</material></gazebo>

    <link name="head">
        <visual>
            <geometry><box size="${head_size} ${head_size} ${head_size}"/></geometry>
            <material name="dora_blue"/>
        </visual>
        <collision>
            <geometry><box size="${head_size} ${head_size} ${head_size}"/></geometry>
        </collision>
        <xacro:box_inertia m="1.0" x="${head_size}" y="${head_size}" z="${head_size}"/>
    </link>
    <gazebo reference="head"><material>Gazebo/SkyBlue</material></gazebo>

    <joint name="neck_joint" type="fixed">
        <parent link="base_link"/>
        <child link="head"/>
        <origin xyz="${torso_len/2 + head_size/2 - 0.05} 0 ${torso_height/2 - head_size/4}" rpy="0 0 0"/>
    </joint>

    <link name="face_mask">
        <visual>
            <geometry><box size="0.01 0.13 0.11"/></geometry>
            <material name="dora_white"/>
        </visual>
    </link>
    <joint name="face_mask_joint" type="fixed">
        <parent link="head"/>
        <child link="face_mask"/>
        <origin xyz="${head_size/2 + 0.001} 0 -0.01" rpy="0 0 0"/>
    </joint>
    <gazebo reference="face_mask"><material>Gazebo/White</material></gazebo>

    <link name="nose">
        <visual>
            <geometry><sphere radius="0.015"/></geometry>
            <material name="dora_red"/>
        </visual>
    </link>
    <joint name="nose_joint" type="fixed">
        <parent link="head"/>
        <child link="nose"/>
        <origin xyz="${head_size/2 + 0.01} 0 0.01" rpy="0 0 0"/>
    </joint>
    <gazebo reference="nose"><material>Gazebo/Red</material></gazebo>

    <link name="left_eye">
        <visual>
            <geometry><sphere radius="0.018"/></geometry>
            <material name="dora_white"/>
        </visual>
    </link>
    <joint name="left_eye_joint" type="fixed">
        <parent link="head"/>
        <child link="left_eye"/>
        <origin xyz="${head_size/2 + 0.005} 0.035 0.035" rpy="0 0 0"/>
    </joint>

    <link name="right_eye">
        <visual>
            <geometry><sphere radius="0.018"/></geometry>
            <material name="dora_white"/>
        </visual>
    </link>
    <joint name="right_eye_joint" type="fixed">
        <parent link="head"/>
        <child link="right_eye"/>
        <origin xyz="${head_size/2 + 0.005} -0.035 0.035" rpy="0 0 0"/>
    </joint>
    <gazebo reference="left_eye"><material>Gazebo/White</material></gazebo>
    <gazebo reference="right_eye"><material>Gazebo/White</material></gazebo>

    <link name="bell">
        <visual>
            <geometry><sphere radius="0.025"/></geometry>
            <material name="dora_yellow"/>
        </visual>
    </link>
    <joint name="bell_joint" type="fixed">
        <parent link="base_link"/>
        <child link="bell"/>
        <origin xyz="${torso_len/2 - 0.02} 0 ${torso_height/2 - 0.02}" rpy="0 0 0"/>
    </joint>
    <gazebo reference="bell"><material>Gazebo/Gold</material></gazebo>

    <xacro:macro name="cat_ear" params="prefix y_pos">
        <link name="${prefix}_ear">
            <visual>
                <geometry><cylinder radius="0.02" length="0.08"/></geometry>
                <material name="dora_blue"/>
            </visual>
        </link>
        <joint name="${prefix}_ear_joint" type="fixed">
            <parent link="head"/>
            <child link="${prefix}_ear"/>
            <origin xyz="0 ${y_pos} ${head_size/2 + 0.04}" rpy="0 0.2 ${y_pos*2}"/> 
        </joint>
        <gazebo reference="${prefix}_ear"><material>Gazebo/SkyBlue</material></gazebo>
    </xacro:macro>
    <xacro:cat_ear prefix="left" y_pos="0.05"/>
    <xacro:cat_ear prefix="right" y_pos="-0.05"/>

    <link name="tail">
        <visual>
            <origin xyz="0.05 0 0" rpy="0 0 0"/>
            <geometry><sphere radius="0.03"/></geometry>
            <material name="dora_red"/>
        </visual>
        <xacro:sphere_inertia m="0.1" r="0.03"/>
    </link>
    <joint name="tail_joint" type="fixed">
        <parent link="base_link"/>
        <child link="tail"/>
        <origin xyz="-${torso_len/2} 0 ${torso_height/2}" rpy="0 0 0"/> 
    </joint>
    <gazebo reference="tail"><material>Gazebo/Red</material></gazebo>

    <xacro:macro name="wheel" params="prefix y_pos">
        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="1.5707 0 0"/>
                <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
                <material name="silver"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="1.5707 0 0"/>
                <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
            </collision>
            <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="-0.1 ${y_pos} -0.05" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </joint>
        <gazebo reference="${prefix}_wheel"><material>Gazebo/Grey</material></gazebo>
    </xacro:macro>

    <xacro:wheel prefix="left" y_pos="0.13"/>
    <xacro:wheel prefix="right" y_pos="-0.13"/>

    <link name="caster_leg">
        <visual>
            <geometry><cylinder radius="0.02" length="0.05"/></geometry>
            <material name="silver"/>
        </visual>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.1"/> <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        </inertial>
    </link>
    <joint name="caster_leg_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_leg"/>
        <origin xyz="0.25 0 -0.05" rpy="0 0 0"/>
    </joint>
    <gazebo reference="caster_leg"><material>Gazebo/Grey</material></gazebo>

    <link name="front_caster">
        <visual>
            <geometry><sphere radius="${caster_radius}"/></geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry><sphere radius="${caster_radius}"/></geometry>
        </collision>
        <xacro:sphere_inertia m="0.2" r="${caster_radius}"/>
    </link>
    
    <joint name="caster_joint" type="fixed">
        <parent link="caster_leg"/>
        <child link="front_caster"/>
        <origin xyz="0 0 -0.04" rpy="0 0 0"/>
    </joint>
    <gazebo reference="front_caster"><material>Gazebo/White</material></gazebo>

    <link name="lidar_stand">
        <visual>
            <geometry><cylinder radius="0.01" length="0.05"/></geometry>
            <material name="silver"/>
        </visual>
        <collision>
            <geometry><cylinder radius="0.01" length="0.05"/></geometry>
        </collision>
        <xacro:cylinder_inertia m="0.05" r="0.01" h="0.05"/>
    </link>

    <joint name="lidar_stand_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_stand"/>
        <origin xyz="0 0 0.10" rpy="0 0 0"/>
    </joint>

    <link name="lidar_link">
        <visual>
            <geometry><cylinder radius="0.035" length="0.02"/></geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry><cylinder radius="0.035" length="0.02"/></geometry>
        </collision>
        <xacro:cylinder_inertia m="0.1" r="0.035" h="0.02"/>
    </link>

    <joint name="lidar_joint" type="fixed">
        <parent link="lidar_stand"/>
        <child link="lidar_link"/>
        <origin xyz="0 0 0.035" rpy="0 0 0"/>
    </joint>

    <gazebo reference="lidar_link">
        <sensor name="lidar" type="gpu_lidar">
            <frame_id>lidar_link</frame_id>
            <pose>0 0 0 0 0 0</pose>
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>40</update_rate>
            <topic>cat/scan</topic>
            <ray>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.15</min> <max>12.0</max>
                </range>
            </ray>
        </sensor>
        <material>Gazebo/Black</material>
    </gazebo>

    <link name="camera_link">
        <visual>
            <geometry><box size="0.01 0.03 0.03"/></geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry><box size="0.01 0.03 0.03"/></geometry>
        </collision>
        <xacro:box_inertia m="0.05" x="0.01" y="0.03" z="0.03"/>
    </link>

    <joint name="camera_joint" type="fixed">
        <parent link="head"/>
        <child link="camera_link"/>
        <origin xyz="${head_size/2 + 0.005} 0 0.06" rpy="0 0 0"/>
    </joint>

    <gazebo reference="camera_link">
        <sensor name="camera" type="camera">
            <camera>
                <horizontal_fov>1.047</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>100</far>
                </clip>
            </camera>
            <always_on>1</always_on>
            <update_rate>30</update_rate>
            <visualize>true</visualize>
            <topic>cat/camera/image_raw</topic>
        </sensor>
    </gazebo>

    <link name="imu_link">
        <visual><geometry><box size="0.01 0.01 0.01"/></geometry></visual>
        <xacro:box_inertia m="0.01" x="0.01" y="0.01" z="0.01"/>
    </link>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <gazebo reference="imu_link">
        <sensor name="imu" type="imu">
            <always_on>true</always_on>
            <update_rate>100</update_rate>
            <topic>cat/imu</topic>
        </sensor>
    </gazebo>

    <gazebo>
        <plugin
            filename="gz-sim-diff-drive-system"
            name="gz::sim::systems::DiffDrive">
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>
            <wheel_separation>0.26</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>
            <odom_publish_frequency>50</odom_publish_frequency>
            
            <topic>cat/cmd_vel</topic>
            <odom_topic>cat/odom</odom_topic>
            <frame_id>cat/odom</frame_id> 
            <child_frame_id>base_link</child_frame_id>

        </plugin>
    </gazebo>

</robot>