<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="cat_robot">

  <!-- PROPERTIES -->
  <xacro:property name="base_width" value="0.25"/>
  <xacro:property name="base_length" value="0.30"/>
  <xacro:property name="base_height" value="0.10"/>
  <xacro:property name="base_mass" value="2.0"/>

  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_mass" value="0.3"/>
  <xacro:property name="wheel_separation" value="0.25"/>

  <!-- MATERIALS -->
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <material name="white">
    <color rgba="1.0 1.0 1.0 1.0"/>
  </material>

  <material name="black">
    <color rgba="0.1 0.1 0.1 1.0"/>
  </material>

  <!-- BASE LINK -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="red"/>
    </visual>

    <collision>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <inertia ixx="${(1/12) * base_mass * (base_width*base_width + base_height*base_height)}" 
               ixy="0.0" ixz="0.0"
               iyy="${(1/12) * base_mass * (base_length*base_length + base_height*base_height)}" 
               iyz="0.0"
               izz="${(1/12) * base_mass * (base_length*base_length + base_width*base_width)}"/>
    </inertial>
  </link>

  <!-- CAT EARS -->
  <link name="left_ear">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.03" length="0.06"/>
      </geometry>
      <material name="white"/>
    </visual>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="left_ear_joint" type="fixed">
    <parent link="base_link"/>
    <child link="left_ear"/>
    <origin xyz="0.10 0.08 ${base_height + 0.03}" rpy="0 0.3 0"/>
  </joint>

  <link name="right_ear">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.03" length="0.06"/>
      </geometry>
      <material name="white"/>
    </visual>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="right_ear_joint" type="fixed">
    <parent link="base_link"/>
    <child link="right_ear"/>
    <origin xyz="0.10 -0.08 ${base_height + 0.03}" rpy="0 0.3 0"/>
  </joint>

  <!-- LEFT WHEEL -->
  <link name="left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <mass value="${wheel_mass}"/>
      <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" 
               ixy="0.0" ixz="0.0"
               iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" 
               iyz="0.0"
               izz="${(1/2) * wheel_mass * wheel_radius * wheel_radius}"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${wheel_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- RIGHT WHEEL -->
  <link name="right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <mass value="${wheel_mass}"/>
      <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" 
               ixy="0.0" ixz="0.0"
               iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width)}" 
               iyz="0.0"
               izz="${(1/2) * wheel_mass * wheel_radius * wheel_radius}"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 ${-wheel_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- LIDAR LINK -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="0.05"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <mass value="0.15"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0.05 0 ${base_height + 0.05}" rpy="0 0 0"/>
  </joint>

  <!-- CAMERA LINK -->
  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.08 0.03"/>
      </geometry>
      <material name="black"/>
    </visual>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${base_length/2} 0 0.05" rpy="0 0 0"/>
  </joint>

  <!-- IMU LINK -->
  <link name="imu_link">
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- GAZEBO PROPERTIES -->
  <gazebo reference="base_link">
    <material>Gazebo/Red</material>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
  </gazebo>

  <gazebo reference="left_ear">
    <material>Gazebo/White</material>
  </gazebo>

  <gazebo reference="right_ear">
    <material>Gazebo/White</material>
  </gazebo>

  <gazebo reference="left_wheel">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
  </gazebo>

  <gazebo reference="right_wheel">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
  </gazebo>

  <gazebo reference="lidar_link">
    <material>Gazebo/Black</material>
  </gazebo>

  <!-- LIDAR SENSOR -->
  <gazebo reference="lidar_link">
    <sensor name="cat_lidar" type="gpu_lidar">
      <pose>0 0 0 0 0 0</pose>
      <topic>cat/scan</topic>
      <update_rate>10</update_rate>
      <lidar>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.15</min>
          <max>12.0</max>
        </range>
      </lidar>
      <always_on>true</always_on>
      <visualize>true</visualize>
    </sensor>
  </gazebo>

  <!-- CAMERA SENSOR -->
  <gazebo reference="camera_link">
    <sensor name="cat_camera" type="camera">
      <pose>0 0 0 0 0 0</pose>
      <topic>cat/camera</topic>
      <update_rate>30</update_rate>
      <camera>
        <horizontal_fov>1.047</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <format>R8G8B8</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>100</far>
        </clip>
      </camera>
      <always_on>true</always_on>
      <visualize>false</visualize>
    </sensor>
  </gazebo>

  <!-- IMU SENSOR -->
  <gazebo reference="imu_link">
    <sensor name="cat_imu" type="imu">
      <topic>cat/imu</topic>
      <update_rate>100</update_rate>
      <always_on>true</always_on>
    </sensor>
  </gazebo>

  <!-- DIFFERENTIAL DRIVE -->
  <gazebo>
    <plugin filename="gz-sim-diff-drive-system" name="gz::sim::systems::DiffDrive">
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>
      <max_linear_velocity>0.5</max_linear_velocity>
      <max_angular_velocity>2.0</max_angular_velocity>
      <odom_publish_frequency>50</odom_publish_frequency>
      <topic>cat/cmd_vel</topic>
      <odom_topic>cat/odom</odom_topic>
      <frame_id>odom</frame_id>
      <child_frame_id>cat_robot/base_link</child_frame_id>
    </plugin>
  </gazebo>

</robot>
