<?xml version="1.0"?>
<robot name="squeak_mouse" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="body_len" value="0.15"/>
    <xacro:property name="body_width" value="0.10"/>
    <xacro:property name="body_height" value="0.06"/>
    <xacro:property name="body_mass" value="0.5"/>

    <xacro:property name="wheel_radius" value="0.035"/>
    <xacro:property name="wheel_width" value="0.01"/>
    <xacro:property name="wheel_mass" value="0.1"/>

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>
    <material name="pink">
        <color rgba="1 0.6 0.6 1"/> </material>
    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <xacro:macro name="box_inertia" params="m x y z">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
                     iyy="${m*(x*x+z*z)/12}" iyz="0"
                     izz="${m*(x*x+y*y)/12}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
                     iyy="${m*(3*r*r+h*h)/12}" iyz="0"
                     izz="${m*r*r/2}"/>
        </inertial>
    </xacro:macro>
    
    <xacro:macro name="sphere_inertia" params="m r">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${2*m*r*r/5}" ixy="0" ixz="0"
                     iyy="${2*m*r*r/5}" iyz="0"
                     izz="${2*m*r*r/5}"/>
        </inertial>
    </xacro:macro>

    <link name="base_link">
        <visual>
            <geometry><box size="${body_len} ${body_width} ${body_height}"/></geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry><box size="${body_len} ${body_width} ${body_height}"/></geometry>
        </collision>
        <xacro:box_inertia m="${body_mass}" x="${body_len}" y="${body_width}" z="${body_height}"/>
    </link>
    
    <gazebo reference="base_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <xacro:macro name="ear" params="prefix y_pos">
        <link name="${prefix}_ear">
            <visual>
                <origin xyz="0 0 0" rpy="1.5707 0 0"/>
                <geometry><cylinder radius="0.03" length="0.005"/></geometry>
                <material name="pink"/>
            </visual>
            <xacro:cylinder_inertia m="0.05" r="0.03" h="0.005"/>
        </link>

        <joint name="${prefix}_ear_joint" type="fixed">
            <parent link="base_link"/>
            <child link="${prefix}_ear"/>
            <origin xyz="0.04 ${y_pos} ${body_height/2 + 0.02}" rpy="0 0 0"/>
        </joint>
        
        <gazebo reference="${prefix}_ear">
            <material>Gazebo/RedBright</material>
        </gazebo>
    </xacro:macro>

    <xacro:ear prefix="left" y_pos="0.04"/>
    <xacro:ear prefix="right" y_pos="-0.04"/>

    <link name="tail">
        <visual>
            <origin xyz="-0.06 0 0" rpy="0 1.57 0"/> <geometry><cylinder radius="0.005" length="0.12"/></geometry>
            <material name="pink"/>
        </visual>
        <xacro:cylinder_inertia m="0.05" r="0.005" h="0.12"/>
    </link>
    
    <joint name="tail_joint" type="fixed">
        <parent link="base_link"/>
        <child link="tail"/>
        <origin xyz="-${body_len/2} 0 0" rpy="0 0 0.2"/> </joint>

    <xacro:macro name="wheel" params="prefix y_pos">
        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0 0 0" rpy="1.5707 0 0"/>
                <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="1.5707 0 0"/>
                <geometry><cylinder radius="${wheel_radius}" length="${wheel_width}"/></geometry>
            </collision>
            <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}"/>
        </link>

        <joint name="${prefix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="0.03 ${y_pos} -0.02" rpy="0 0 0"/> <axis xyz="0 1 0"/>
        </joint>
        
        <gazebo reference="${prefix}_wheel">
            <material>Gazebo/Black</material>
        </gazebo>
    </xacro:macro>

    <xacro:wheel prefix="left" y_pos="0.06"/>
    <xacro:wheel prefix="right" y_pos="-0.06"/>

    <link name="caster_wheel">
        <visual>
            <geometry><sphere radius="${wheel_radius/2}"/></geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry><sphere radius="${wheel_radius/2}"/></geometry>
        </collision>
        <xacro:sphere_inertia m="0.05" r="${wheel_radius/2}"/>
    </link>

    <joint name="caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel"/>
        <origin xyz="-0.06 0 -0.035" rpy="0 0 0"/>
    </joint>

    <gazebo reference="caster_wheel">
        <mu1>0.001</mu1>
        <mu2>0.001</mu2>
        <material>Gazebo/Black</material>
    </gazebo>
	<link name="lidar_link">
        <visual>
            <geometry><cylinder radius="0.035" length="0.02"/></geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry><cylinder radius="0.035" length="0.02"/></geometry>
        </collision>
        <xacro:cylinder_inertia m="0.1" r="0.035" h="0.02"/>
    </link>

    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="0 0 ${body_height/2 + 0.01}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="lidar_link">
        <sensor name="lidar" type="gpu_lidar">
			<frame_id>lidar_link</frame_id>
            <pose>0 0 0 0 0 0</pose>
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>40</update_rate>
            <topic>scan</topic>
            <ray>
                <scan>
                    <horizontal>
                        <samples>720</samples>
                        <resolution>1</resolution>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.15</min> <max>12.0</max>
                </range>
            </ray>
        </sensor>
        <material>Gazebo/Black</material>
    </gazebo>
	
	<link name="camera_link">
        <visual>
            <geometry><box size="0.01 0.03 0.03"/></geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry><box size="0.01 0.03 0.03"/></geometry>
        </collision>
        <xacro:box_inertia m="0.05" x="0.01" y="0.03" z="0.03"/>
    </link>

    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="${body_len/2} 0 0" rpy="0 0 0"/>
    </joint>

    <gazebo reference="camera_link">
        <sensor name="camera" type="camera">
            <camera>
                <horizontal_fov>1.047</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>100</far>
                </clip>
            </camera>
            <always_on>1</always_on>
            <update_rate>30</update_rate>
            <visualize>true</visualize>
            <topic>camera/image_raw</topic>
        </sensor>
    </gazebo>
	
	<link name="imu_link">
        <visual><geometry><box size="0.01 0.01 0.01"/></geometry></visual>
        <xacro:box_inertia m="0.01" x="0.01" y="0.01" z="0.01"/>
    </link>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <gazebo reference="imu_link">
        <sensor name="imu" type="imu">
            <always_on>true</always_on>
            <update_rate>100</update_rate>
            <topic>imu</topic>
        </sensor>
    </gazebo>

	<gazebo>
        <plugin
            filename="gz-sim-diff-drive-system"
            name="gz::sim::systems::DiffDrive">
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>
            <wheel_separation>0.12</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>
            <odom_publish_frequency>50</odom_publish_frequency>
            <topic>cmd_vel</topic>
            <odom_topic>odom</odom_topic>
            <frame_id>odom</frame_id>
        </plugin>
    </gazebo>


</robot>